### ISSUE TITLE
Broken OreDict

### ISSUE THREAD

**Issue by BlazingGamer** [TeamMetallurgy/Metallurgy4#76]
When I launch MC my log is filled with these messages:
[18:06:24] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name ingotSilver has occurred. It adds an item (type: class com.teammetallurgy.metallurgy.metals.MetalItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Metallurgy 4 report it to them!
[18:06:24] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[18:06:24] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[18:06:24] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.metals.MetalSet.load(MetalSet.java:390)
[18:06:24] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.BlockList.injectMetalSet(BlockList.java:216)
[18:06:24] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.BlockList.initMetalSets(BlockList.java:178)
[18:06:24] [Client thread/WARN] [FML]: *  at com.teammetallurgy.metallurgy.BlockList.init(BlockList.java:105)...

**Comment by Glassmaker** [comment]
Fixed on 995bcde 
Will be released soon :)
