### ISSUE TITLE
metals registered wrong in forge or something

### ISSUE THREAD

**Issue by 31trainman** [TeamMetallurgy/Metallurgy4#79]
Here is the text I'm seeing. It happens with all the metals in metallurgy

[09:56:34] [Client thread/WARN]: ****************************************
[09:56:34] [Client thread/WARN]: * A broken ore dictionary registration with name ingotCopper has occurred. It adds an item (type: class com.teammetallurgy.metallurgy.metals.MetalItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Metallurgy 4 report it to them!
[09:56:34] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[09:56:34] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[09:56:34] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.metals.MetalSet.load(MetalSet.java:390)
[09:56:34] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.BlockList.injectMetalSet(BlockList.java:216)
[09:56:34] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.BlockList.initMetalSets(BlockList.java:178)
[09:56:34] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.BlockList.init(BlockList.java:105)...
[09:56:34] [Client thread/WARN]: ****************************************

Metallurgy-1.7.10-4.0.8.97
MetallurgyCore-1.7.10-4.0.4.18

Forge 1614
Java 8
Mac os x El Capitan
mc 1.7.10

Mods:
  AdvancedSolarPanel-1.7.10-3.5.1
  ATG-1.7.10-0.12.0
  AMT_Generators-1.7.10-1.4.2
  AOBD-2.9.1
  AOBDBB-1.0.6
  AppleMilkTea2-1.7.10_2.9k
  appliedenergistics2-rv3-beta-5
  AsieLib-1.7.10-0.4.5
  BiblioCraft[v1.11.4][MC1.7.10]
  BiblioWoods[Forestry][v1.7]
  BiblioWoods[Natura][v1.5]
  BigDoors-1.7.10-1.1.0
  BigReactors-0.4.3A
  buildcraft-7.1.16
  BuildcraftAdditions-1.7.10-2.2.5
  buildcraft-compat-7.1.4
  Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10
  PFAA-1.7.10-0.2.27
  Chisel2-2.5.1.44
  ChiselTones-1.7.10-1.0-3
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.2-325
  ComputerCraft1.75
  Computronics-1.7.10-1.6.0
  CookieCore-1.7.10-1.4.0-11
  CustomOreGen-1.7.10-1.2.24
  Draconic-Evolution-1.7.10-1.0.2-RC2
  DragonAPI 1.7.10 V11b
  ElecCore-1.7.10-1.4.176
  ElectricalAge_BETA-1.10_r50
  Enchiridion 2-1.7.10-2.0.2a
  EnderIO-1.7.10-2.3.0.424_beta
  EnderZoo-1.7.10-1.0.15.32
  EnderCore-1.7.10-0.2.0.31_beta
  Enhanced Biomes 2.5 for MC 1.7.10
  Eureka-1.7.10-3.0.2
  BrandonsCore-1.0.0.11
  INpureCore-[1.7.10]1.0.0B9-62
  ExtraCells-1.7.10-2.3.9b188
  extrautilities-1.2.12
  ExtraTiC-1.7.10-1.4.5
  Farseek-1.0.11
  fastcraft-1.21
  FlenixCitiesCore_[1.7.10]-0.16.1-b122
  FlenixCitiesFood_[1.7.10]-0.5
  FlenixCitiesResearch_[1.7.10]-0.4
  FlenixRoads_[1.7.10]-0.9.0
  forestry_1.7.10-4.2.10.58
  FrameCompanion-1.1
  GardenStuff-1.7.10-1.7.0
  Guide-API-1.7.10-1.0.1-29
  HydCraft-1.7.10-2.1.253-universal
  ImmersiveEngineering-0.7.4
  immersiveintegration-0.6.7
  IGW-Mod-1.7.10-1.1.12-34-universal
  industrialcraft-2-2.2.817-experimental
  InventoryTweaks-1.59-dev-152
  IvToolkit-1.2
  k4lib-1.7.10-0.1.57-universal
  logisticspipes-0.9.3.99
  ModularPowersuits-0.11.0.300
  magneticraft-0.6.1-final
  malisisdoors-1.7.10-1.13.2
  malisisadvert-1.7.10-0.5.0
  malisiscore-1.7.10-0.14.3
  Mantle-1.7.10-0.3.2b
  Mariculture-Deluxe-1.7.10-1.2.4.2a
  Mekanism-1.7.10-8.1.9.265
  MekanismGenerators-1.7.10-8.1.9.265
  MekanismTools-1.7.10-8.1.9.265
  Metallurgy-1.7.10-4.0.8.97
  MetallurgyCore-1.7.10-4.0.4.18
  Minechem-1.7.10-5.0.5.406
  MineFactoryReloaded-[1.7.10]2.8.2B1-177
  natura-1.7.10-2.2.1a2
  neiaddons-1.12.15.41-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NGTLib1.7.10.20_Forge10.13.4.1558
  NotEnoughResources-1.7.10-0.1.0-122
  NotEnoughItems-1.7.10-1.0.5.118-universal
  IC2NuclearControl-2.3.4a
  Numina-0.4.0.131
  OpenBlocks-1.7.10-1.5.1
  OpenComputers-MC1.7.10-1.6.0.1-beta.1-universal
  OpenModsLib-1.7.10-0.9.1
  OpenPeripheral-1.7.10-AIO-7
  OpenSecurity-1.7.10-1.0-91
  Pam's HarvestCraft 1.7.10Lb
  PlanetguyLib-1.9.1
  PneumaticCraft-1.7.10-1.12.7-150-universal
  ProjectBlue-1.1.6-mc1.7.10
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-World
  ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  QuantumFlux-1.7.10-1.3.4
  Railcraft_1.7.10-9.9.0.0
  ReactorCraft 1.7.10 V11b
  RTG-1.7.10-0.7.0
  RemainInMotion-2.8.9
  RemoteIO-1.7.10-2.4.0-universal
  RotaryCraft 1.7.10 V11b
  RTM1.7.10.27_Forge10.13.4.1558
  Streams-0.2
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.1.2-240
  ThermalFoundation-[1.7.10]1.2.3-112
  ThermalRecycling-1.7.10-1.1.0.5
  TiCTooltips-mc1.7.10-1.2.5
  tinker_io-1.7.10-release 1.5.0
  TConstruct-1.7.10-1.8.8
  TSteelworks-1.7.10-1.1.2-20
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.10-1.1.6
  WR-CBE-1.7.10-1.4.1.9-universal
  YeGamolChattels-1.1.2
  zettaindustries-1.1-106
  Zora no Densha_v0.8_snapshot_Nov2015_MC 1.7.10
  Ztones-1.7.10-2.2.1

**Comment by Sinhika** [comment]
I'm seeing the same issue.  I think you are setting up your ore dictionary entries too early.

Example snipped from log:
`[08:31:16] [Client thread/WARN]: ****************************************
[08:31:16] [Client thread/WARN]: * A broken ore dictionary registration with name ingotCopper has occurred. It adds an item (type: class com.teammetallurgy.metallurgy.metals.MetalItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Metallurgy 4 report it to them!
[08:31:16] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[08:31:16] [Client thread/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[08:31:16] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.metals.MetalSet.load(MetalSet.java:390)
[08:31:16] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.BlockList.injectMetalSet(BlockList.java:216)
[08:31:16] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.BlockList.initMetalSets(BlockList.java:178)
[08:31:16] [Client thread/WARN]: *  at com.teammetallurgy.metallurgy.BlockList.init(BlockList.java:105)...
`

The same type of messages repeat for all the ingots.

**Comment by 31trainman** [comment]
Im developing a modpack and seeing this get put in my console. Im not developing a mod.

**Comment by Calendis** [comment]
Doesn't happen in forge 1492, but it happens it later versions.

**Comment by 31trainman** [comment]
I'm using forge 1614

**Comment by Glassmaker** [comment]
Fixed on 995bcde 
Will be released soon :)
